### PR TITLE
25 refactor canon eos support

### PR DESCRIPTION
**Pull request by gkoh**

### CODE REVIEW

**Comment by gkoh** [comment]
@wolcano Are you in a position to test this PR?
I've refactored the code so M6 and RP share code now.
Additionally, I was looking at other projects and I seem to recall what I called 'shutterPress' is actually 'focus'.
So, I've broken it up for both Fuji and Canon, there's now 'shutterPress/shutterRelease' and 'focusPress/focusRelease'.

If I'm right, button 'A' will now:
* trigger focus
* trigger the shutter

And button 'B' will:
* trigger focus only

**Comment by wolcano** [comment]
both A and B focus and trigger shutter

**Comment by gkoh** [comment]
> both A and B focus and trigger shutter

Damn, guess I’m wrong. Thanks for trying.

**Comment by gkoh** [comment]
> > both A and B focus and trigger shutter
> 
> Damn, guess I’m wrong. Thanks for trying.

I created #29 to track this properly.
I think this refactor is worth merging as-is.

**Pull request merged**
